export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as Icons } from './Icons';
export { default as NotFound } from './NotFound';
export { default as ProductList } from './ProductList';
export { default as Settings } from './Settings';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Typography } from './Typography';
export { default as UserList } from './UserList';
export {default as CenterList} from './Center';
export {default as TeacherList} from './Teacher';
export { default as BaseSalary } from './BaseSalary';
export { default as Room } from './Room';
export { default as Courses } from './Courses';
export { default as Classes } from './Classes';
export { default as Relationship } from './Relationship';
export { default as Step } from './Step';
export { default as Status } from './Status';
export { Entrance } from './Entrance';
export { CreateEntrance, ViewEntrance } from './Entrance';
